gui:
    # Catppuccin Mocha theme
    theme:
        activeBorderColor:
            - "#89b4fa" # Blue
            - bold
        inactiveBorderColor:
            - "#a6adc8" # Subtext0
        optionsTextColor:
            - "#89b4fa" # Blue
        selectedLineBgColor:
            - "#313244" # Surface0
        selectedRangeBgColor:
            - "#313244" # Surface0
        cherryPickedCommitBgColor:
            - "#45475a" # Surface1
        cherryPickedCommitFgColor:
            - "#89b4fa" # Blue
        unstagedChangesColor:
            - "#f38ba8" # Red
        defaultFgColor:
            - "#cdd6f4" # Text
        searchingActiveBorderColor:
            - "#f9e2af" # Yellow
    showFileTree: true # File tree on the left
    showRandomTip: false
    showBottomLine: true
    showCommandLog: true
    showIcons: true
git:
    paging:
        colorArg: always
        useConfig: true
    commit:
        signOff: false
    merging:
        manualCommit: false
        args: ""
    skipHookPrefix: WIP
    autoFetch: true
    branchLogCmd: "git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium {{branchName}} --"
    allBranchesLogCmd: "git log --graph --all --color=always --abbrev-commit --decorate --date=relative  --pretty=medium"
    overrideGpg: false
update:
    method: prompt # can be: prompt | background | never
    days: 14 # how often an update is checked for
reporting: "off"
confirmOnQuit: false
# Keybindings
keybinding:
    universal:
        quit: "q"
        quit-alt1: "<c-c>"
        return: "<esc>"
        quitWithoutChangingDirectory: "Q"
        togglePanel: "<tab>"
        prevItem: "<up>"
        nextItem: "<down>"
        prevPage: ","
        nextPage: "."
        gotoTop: "<"
        gotoBottom: ">"
        prevBlock: "<left>"
        nextBlock: "<right>"
        nextMatch: "n"
        prevMatch: "N"
        startSearch: "/"
        optionMenu: "?"
        edit: "e"
        new: "n"
        scrollUpMain: "<pgup>"
        scrollDownMain: "<pgdown>"
        scrollUpMain-alt1: "K"
        scrollDownMain-alt1: "J"
        executeShellCommand: ":"
        createRebaseOptionsMenu: "m"
        pushFiles: "P"
        pullFiles: "p"
        refresh: "R"
        createPatchOptionsMenu: "<c-p>"
        nextTab: "]"
        prevTab: "["
        nextScreenMode: "+"
        prevScreenMode: "_"
        undo: "u"
        redo: "<c-r>"
        filteringMenu: "<c-f>"
        diffingMenu: "W"
        copyToClipboard: "y"
        openRecentRepos: "<c-r>"
        submitEditorText: "<enter>"
        extrasMenu: "@"
        toggleWhitespaceInDiffView: "<c-w>"
        increaseContextInDiffView: "}"
        decreaseContextInDiffView: "{"
customCommands:
    - key: "H"
      command: "git commit --amend --no-edit"
      context: "commits"
      loadingText: "Amending..."
      description: "amend commit without editing message"
    - key: "C"
      command: "git cz"
      context: "files"
      loadingText: "committing with commitizen..."
      description: "commit with commitizen"
      stream: yes
os:
    editCommand: "nvim"
    editCommandTemplate: "{{editor}} +{{line}} -- {{filename}}"
    openCommand: "code"
